[project]
name = "ai-tutorial-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.67.0",
    "google-generativeai>=0.8.6",
    "opencv-python>=4.13.0.92",
    "pynput>=1.8.1",
    "scenedetect[opencv]>=0.6.7.1",
    "scikit-image>=0.26.0",
]
